version: "3"
services:
  smtp-server:
    image: mailhog/mailhog
    container_name: smtp-server
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mail-volumes:/tmp
  pop-imap-server:
    build: ./dovecot
    container_name: pop-imap-server
    ports:
      - "143:31143"
      - "110:31110"
    volumes:
      - mail-volumes:/srv/vmail
      - ./dovecot:/etc/dovecot/conf.d
volumes:
  mail-volumes:
